# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 22:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_remove_evpoint_highlighted'),
    ]

    operations = [
        migrations.CreateModel(
            name='EVTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('time_start', models.IntegerField()),
                ('time_end', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evtrip', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
