# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_evtrip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evpoint',
            name='latitude',
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
        migrations.AlterField(
            model_name='evpoint',
            name='longitude',
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
        migrations.AlterField(
            model_name='evpoint',
            name='speed',
            field=models.DecimalField(decimal_places=8, max_digits=15),
        ),
    ]
